### ISSUE TITLE
⛰️ [Epic] Feature Planning: Interop with hosted Airbyte: Cloud, OSS, and Enterprise

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte#111]
```[tasklist]
### Tasks
- [ ] https://github.com/airbytehq/PyAirbyte/issues/33
- [ ] https://github.com/airbytehq/PyAirbyte/issues/104
- [ ] https://github.com/airbytehq/PyAirbyte/issues/110
```
