### ISSUE TITLE
Align column and table normalization with Dv2 destinations

### ISSUE THREAD

**Issue by flash1293** [airbytehq/PyAirbyte#14]
To allow easy migration from airbyte-lib to hosted Airbyte, the logic to generate table and column names as well as column types need to be identical to the logic used in Java destinations.

This might already be the case in a lot of situations, but we need to make sure edge cases are handled properly, like weird characters in column and table names.
```[tasklist]
### Tasks
- [ ] Confirm the common special chars are handled consistently (['-', '_', '.'])
- [ ] Confirm that casing is handled consistently
- [ ] Confirm other more random special chars are handled consistently (emoji, punctuation, non-latin characters, chars with accents, etc.)
```

----

From @aaronsteers 

## Reference Pages Available

These pages can be used to confirm the Dv2-compatible table schema requirements:

- [Upgrading to Destinations V2 | Airbyte Documentation](https://docs.airbyte.com/release_notes/upgrading_to_destinations_v2)
- [Typing and Deduping | Airbyte Documentation](https://docs.airbyte.com/using-airbyte/core-concepts/typing-deduping)

Quotes:

From [Notion](https://www.notion.so/Airbyte-Data-Warehouse-Destination-V2-Philosophy-e6081edb87084999948acdc8b9607ea1?pvs=4#18fa03d3e9a7416d8049fd9ce7370958):

> ### Notes on name transformations and per-destination rules
> 
> As a rule, we try to keep schema, table, and column names as close as possible to the source, but there are sometimes exceptions:
>
> - Spaces are not allowed and should be replaced with `_`
> - Capital letters *are* maintained in table or column names
> - Some destinations have case-sensitive conventions, e.g. Snowflake prefers UPPERCASE schemas, tables, and columns.  Learn more at [[Database Facts](https://www.notion.so/Database-Facts-4a68926d3acf46d2a65890f60f767472?pvs=21)](https://www.notion.so/Database-Facts-4a68926d3acf46d2a65890f60f767472?pvs=21).

**Comment by aaronsteers** [comment]
This will also require us to be able to add missing columns to a cache table when those columns don't already exist.
