### ISSUE TITLE
Apply security and compatibility updates for PyAirbyte dependencies (Sep 2024)

### ISSUE THREAD

**Issue by aaronsteers** [airbytehq/PyAirbyte#386]
There are a number of dependencies of PyAirbyte which are stale relative to security updates. We'd also like to build a formal process to stay on top of relevant security and dependency updates.

This issue will track a number of action items:

```[tasklist]
### Tasks
- [x] Enable GitHub security scanning
- [x] Enable dependabot in GitHub
- [x] Handle initial of dependabot recommendations
- [ ] #382
- [ ] https://github.com/airbytehq/PyAirbyte/pull/383
- [x] Make issues for any other remaining long-term action items
- [ ] https://github.com/airbytehq/PyAirbyte/pull/396
- [ ] https://github.com/airbytehq/PyAirbyte/issues/397
- [ ] https://github.com/airbytehq/PyAirbyte/issues/398
```

**Comment by aaronsteers** [comment]
As noted in task list above, this week we enabled dependabot updates and GitHub security scanning.

We've also merged 9 [dependabot updates](https://github.com/airbytehq/PyAirbyte/pulls?q=is:pr+is:closed+%22Chore(deps)%22) this week, which will release shortly.

**Comment by aaronsteers** [comment]
Just released:

- Patch release with low-hanging fruit dependabot updates:
  - https://github.com/airbytehq/PyAirbyte/releases/tag/v0.17.8

**Comment by aaronsteers** [comment]
The latest version of PyAirbyte,, released today, includes support for SQLalchemy 2.0 along with the latest version of the Airbyte CDK, along with several other dependency updates. 


https://github.com/airbytehq/PyAirbyte/releases/tag/v0.17.9

Closing this issue as resolved for our high pri updates. New issues have been created to track Pendulum and `jsonschema`.

Any other dependency updates that are needed may be requested by creating a new GitHub issue here in this repo.
